version: '3.7'

services:
  ######################################################################

  # docker-compose -f ./dev.docker-compose.yml stop cms-museu-backend
  # docker-compose -f ./dev.docker-compose.yml rm -f cms-museu-backend
  # docker-compose -f ./dev.docker-compose.yml up --build cms-museu-backend
  # docker-compose -f ./dev.docker-compose.yml start cms-museu-backend
  # docker-compose -f ./dev.docker-compose.yml logs -f --tail="5000" cms-museu-backend

  cms-museu-backend:
    image: cms-museu-backend-image
    container_name: cms-museu-backend
    build:
      context: .
      target: development
      dockerfile: ./dev/backend.dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: npm run start:dev
    environment:
      - DATABASE_URL=mysql://root:root@cms-museu-database:3306/cms-museu-db?useTimezone=true&serverTimezone=UTC&connection_limit=15&socket_timeout=5
      - NODE_ENV=development

  ######################################################################

  # docker-compose -f ./dev.docker-compose.yml stop cms-museu-database
  # docker-compose -f ./dev.docker-compose.yml rm -f cms-museu-database
  # docker-compose -f ./dev.docker-compose.yml up --build cms-museu-database
  # docker-compose -f ./dev.docker-compose.yml start -d cms-museu-database
  # docker-compose -f ./dev.docker-compose.yml logs -f --tail="5000" cms-museu-database

  cms-museu-database:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./dev/database.dockerfile
    image: cms-museu-database-image
    container_name: cms-museu-database
    environment:
      - ENV_PORT=3307
      - ENV_MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - ENV_MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306